#
# server build.
# ex) $ docker-compose build --no-cache
#
# server start.
# ex) $ docker-compose up -d
#
version: '3'
services:
  httpd:
    build: ./docker/httpd/
    image: my/apache2.4
    container_name: 'httpd'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - app:/var/www/www.example.com:cached

  php:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    image: my/php7.2
    container_name: 'php'
    tty: true
    ports:
      - '9000:9000'
    volumes:
      - app:/var/www/www.example.com:cached

volumes:
  app:
    driver: local

