#
# server build.
# ex) $ docker-compose build --no-cache
#
# server start.
# ex) $ docker-compose up -d
#
version: '3'
services:
  httpd:
    build: ./docker/httpd/
    image: my/apache2.4
    container_name: 'httpd'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - app:/var/www/www.example.com:cached

  php:
    image: my-laravel5.6/php:7.3
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    tty: true
    ports:
      - '9000:9000'
    volumes:
      - app:/var/www/www.example.com:cached
      - vendor:/var/www/www.example.com/vendor/
      - node_modules:/var/www/www.example.com/node_modules/
    depends_on:
      - mysql


  node:
    image: node:11.11
    container_name: 'node'
    working_dir: /var/www/www.example.com/
    volumes:
      - app:/var/www/www.example.com:cached
      - node_modules:/var/www/www.example.com/node_modules/
    depends_on:
      - php

  mailhog:
    image: mailhog/mailhog
    container_name: 'mailhog'
    ports:
      - "8025:8025"

  mysql:
    build: ./docker/mysql/
    image: my/mysql5.7
    container_name: 'mysql'
    environment:
      - MYSQL_DATABASE=mysql
      - MYSQL_ROOT_PASSWORD=development
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/example.sql:/docker-entrypoint-initdb.d/example.sql

volumes:
  app:
    driver_opts:
      type: none
      device: ${PWD}/src/
      o: bind

  vendor:
    driver: local

  node_modules:
    driver: local

  mysql-data:
    driver: local
